site_name: HobbitQia的笔记本
site_url: https://note.hobbitqia.cc/
repo_name: HobbitQia/notebook  #存储库名称，一般自动设置
repo_url: https://github.com/HobbitQia/notebook/  #存储库URL
# edit_uri: tree/master/docs  #每个文档的顶部显示一个编辑按钮，""则隐藏
site_description: HobbitQia的笔记本
copyright: Copyright &copy; 2022 <a href="https://github.com/HobbitQia"  target="_blank" rel="noopener">HobbitQia</a>

theme: 
  name: material
  language: zh
  logo: log.ico
  favicon: log.ico
  custom_dir: overrides
  features:
    - content.code.annotate
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
    - navigation.top
  font:
    text: LXGW WenKai Screen
    code: JetBrains Mono
  palette:     #切换昼夜模式的颜色，审美差就用默认，专业点就自定义
    - media: "(prefers-color-scheme: light)" 
      scheme: default  #配色方案：浅色模式
      primary: Brown  #原色，默认蓝，用于标题、侧边栏、文本链接和其他几个组件
      accent: Brown  #强调色，默认蓝，可以交互的元素如悬停链接、按钮和滚动条
      toggle:
        icon: material/weather-sunny #图标，太阳
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"  
      scheme: slate  #配色方案：深色模式
      # primary: Brown  #原色，默认蓝，用于标题、侧边栏、文本链接和其他几个组件
      toggle:
        icon: material/weather-night  #图标，月亮
        name: Switch to light mode


markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 4
  - meta
  - def_list
  - attr_list
  - md_in_html
  - sane_lists
  - admonition
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.smartsymbols  #智能符号
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: true


extra_css:
  - https://gcore.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.css
  - https://gcore.jsdelivr.net/npm/lxgw-wenkai-screen-webfont@1.1.0/style.css
  - https://gcore.jsdelivr.net/npm/lxgw-wenkai-webfont@1.1.0/style.css
  - css/custom.css
  - css/card.css
  - css/tasklist.css
  

extra_javascript:
  - https://gcore.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.js
  - js/katex.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/HobbitQia/

plugins:
  - search
  - git-revision-date-localized:
      type: datetime
      timezone: Asia/Shanghai
      locale: zh
      enable_creation_date: true
      exclude:
        - index.md
        - comming.md
        - link.md
        - tech_accu/index.md
        - cour_note/index.md

nav:
  - Home:
    - index.md
  - Computer Science:
    - 计算机系统概论: 
      - ICS/index.md
      - Introduction: ICS/ICS-1.md
      - Bits, Data Types and Operations: ICS/ICS-2.md
      - Digital Logic Structures: ICS/ICS-3.md
      - The von Neumann Model: ICS/ICS-4.md
      - LC-3: ICS/ICS-5.md
      - Programming: ICS/ICS-6.md
      - Assembly Language: ICS/ICS-7.md
      - Data Structures: ICS/ICS-8.md
      - I/0: ICS/ICS-9.md
    - CSAPP:
      - 优化程序性能: CSAPP/5.md
      - 存储器层次结构: CSAPP/6.md
      - 链接: CSAPP/7.md
      - 异常控制流: CSAPP/8.md
      - 虚拟内存: CSAPP/9.md
    - 计算机逻辑设计基础: 
      - Logic/index.md
      - 数字系统和信息: Logic/logic01.md
      - 组合逻辑电路: Logic/logic02.md
      - 组合逻辑电路设计: Logic/logic03.md
      - 时序逻辑电路: Logic/logic04.md
      - 寄存器与寄存器传输: Logic/logic06.md
      - 数字硬件设计: Logic/logic05.md
      - 内存基础: Logic/logic07.md
    - 数据结构与算法: 
      - ds/index.md
      - 算法分析: ds/algorithm.md
      - 树: ds/tree.md
      - 堆: ds/heap.md
      - 并查集: ds/set.md
      - 图论: ds/graph.md
      - 排序: ds/sort.md
      - 散列: ds/hash.md
    - 图像信息处理:
      - dip/index.md
      - 图像信息处理介绍: dip/dip1.md
      - 二值图像和形态学: dip/dip2.md
      - 图像灰度变换与直方图: dip/dip3.md
      - 几何变换: dip/dip5.md
      - 卷积与滤波: dip/dip6.md
      - 双边滤波的加速: dip/dip7.md
      - 引导滤波: dip/dip8.md
      - 稀疏范数滤波: dip/dip9.md
      - 傅里叶变换: dip/dip10.md
      - 图像特征检测和提取: dip/dip11.md
      - 深度学习: dip/dip12.md
    - 面向对象程序设计: 
      - Introduction: OOP/oop1.md
      - Class: OOP/oop2.md
      - Container: OOP/oop3.md
      - Function: OOP/oop4.md
      - Constant and Static: OOP/oop5.md
      - Inheritance: OOP/oop6.md
      - Polymorphism: OOP/oop7.md
      - Copy Ctor: OOP/oop8.md
      - Overloaded Operators: OOP/oop9.md
      - Templates: OOP/oop10.md
    - 数据库系统:
      - 数据库介绍: DB/db1.md
      - 关系模型: DB/db2.md
      - SQL 语言介绍: DB/db3.md
      - 中级 SQL: DB/db4.md
      - 高级 SQL: DB/db5.md
      - 实体-关系模型: DB/db6.md
      - 关系数据库设计: DB/db7.md
      - 物理存储系统: DB/db8.md
      - 数据存储结构: DB/db9.md
      - 索引: DB/db10.md
      - 查询处理: DB/db11.md
    - 计算机组成:
      - 计算机概要与技术: CO/co1.md
      - 计算机的算术运算: CO/co3.md
      - 指令：计算机的语言: CO/co2.md
      - 处理器: CO/co4.md
  - Mathematics:
    - 线性代数: 
      - 线性代数Ⅱ(H): Mathematics/线性代数Ⅱ(H)/Rings.md
    - 数据建模与分析:
      - 感知机: MLT/mlt2.md
  - Miscellaneous:
    - Android:
      - 触控事件的数据流: android/dataflow.md
  - 友链:
    - link.md